admin/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.admin, name="links-admin"),
    path("create/", views.create_link, name="create-link"),
    path("view/<int:pk>/", views.link_detail, name="link-detail"),
    path("delete/<int:pk>", views.DeleteLink.as_view(), name="delete-link"),
    path("login/", auth_views.LoginView.as_view()),
    path("logout/", auth_views.LogoutView.as_view()),
    path(
        "password_change/", auth_views.PasswordChangeView.as_view(success_url="/admin/")
    ),
]

links/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("update/", views.update_visit, name="update-visit"),
    path("<str:short_id>/", views.redirect_to_destination, name="redirect"),
]

redirekt/urls.py
from django.urls import include, path

urlpatterns = [
    path("links/", include("links.urls")),
    path("admin/", include("admin.urls")),
    path("django-rq/", include("django_rq.urls")),
]

links/models.py
from django.db import models


class Link(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=1000)
    collect_extended_data = models.BooleanField(default=True)
    short_id = models.CharField(max_length=6, unique=True)
    destination = models.URLField()

    def __str__(self):
        return "{} ({})".format(self.title, self.destination)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("link-detail", kwargs={"pk": self.pk})

    def get_delete_url(self):
        from django.urls import reverse

        return reverse("delete-link", kwargs={"pk": self.pk})

    def get_redirect_url(self):
        from django.urls import reverse

        return reverse("redirect", kwargs={"short_id": self.short_id})


class Visit(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    # Core information from the request
    link = models.ForeignKey(Link, on_delete=models.CASCADE)
    ip = models.CharField(max_length=1000)
    user_agent = models.CharField(max_length=4000, null=True)
    language = models.CharField(max_length=1000, null=True)
    referrer = models.CharField(max_length=1000, null=True)
    # From user agent
    device_brand = models.CharField(max_length=1000, null=True)
    device_family = models.CharField(max_length=1000, null=True)
    device_model = models.CharField(max_length=1000, null=True)
    os_family = models.CharField(max_length=1000, null=True)
    os_major = models.CharField(max_length=1000, null=True)
    os_minor = models.CharField(max_length=1000, null=True)
    os_patch = models.CharField(max_length=1000, null=True)
    browser_family = models.CharField(max_length=1000, null=True)
    browser_major = models.CharField(max_length=1000, null=True)
    browser_minor = models.CharField(max_length=1000, null=True)
    browser_patch = models.CharField(max_length=1000, null=True)

    # Generated by us
    is_bot = models.BooleanField(default=False)

    # Details from ipinfo.io
    city = models.CharField(max_length=1000, null=True)
    country = models.CharField(max_length=1000, null=True)
    hostname = models.CharField(max_length=1000, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)

    # Details from JS fingerprint
    fingerprint = models.CharField(max_length=1000)
    fingerprint_fields = models.JSONField(blank=True, default=dict)
    screen_x = models.IntegerField(null=True)
    screen_y = models.IntegerField(null=True)

    class Meta:
        indexes = [models.Index(fields=["fingerprint"])]

links/forms.py
from django import forms

import re

from .models import Link
from .utils import get_random_short_id


class AdminLoginForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")


class LinkForm(forms.ModelForm):

    RESTRICTED_VALUES = ["admin", "delete"]

    class Meta:
        model = Link
        fields = ["title", "destination"]

    def save(self, commit=True):
        instance = super(LinkForm, self).save(commit=False)
        instance.short_id = get_random_short_id()
        if commit:
            instance.save()
        return instance

    def clean_short_id(self):
        data = self.cleaned_data['short_id']

        if data in self.RESTRICTED_VALUES:
            raise ValidationError(
                _("Invalid short ID: %(value)s"),
                code="invalid",
                params={"value": data},
            )
        elif not re.match("^\w+$", data):
            raise ValidationError(
                _("Invalid short ID: %(value)s"),
                code="invalid",
                params={"value": data},
            )

        return data

links/views.py
import json

from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from ipware import get_client_ip
from ua_parser import user_agent_parser

from .models import Link, Visit
from .utils import deep_get, get_ray_id, is_bot


def _save_data_from_request(request, link):
    # try:
    user_agent = request.META.get("HTTP_USER_AGENT")
    user_agent_dict = user_agent_parser.Parse(user_agent)

    language = request.META.get("HTTP_ACCEPT_LANGUAGE")
    referrer = request.META.get("HTTP_REFERER")
    client_ip, _is_routable = get_client_ip(request)
    visit = Visit(
        link=link,
        user_agent=user_agent,
        language=language,
        referrer=referrer,
        device_brand=deep_get(user_agent_dict, ["device", "brand"]),
        device_family=deep_get(user_agent_dict, ["device", "family"]),
        device_model=deep_get(user_agent_dict, ["device", "model"]),
        os_family=deep_get(user_agent_dict, ["os", "family"]),
        os_major=deep_get(user_agent_dict, ["os", "major"]),
        os_minor=deep_get(user_agent_dict, ["os", "minor"]),
        os_patch=deep_get(user_agent_dict, ["os", "patch"]),
        browser_family=deep_get(user_agent_dict, ["user_agent", "family"]),
        browser_major=deep_get(user_agent_dict, ["user_agent", "major"]),
        browser_minor=deep_get(user_agent_dict, ["user_agent", "minor"]),
        browser_patch=deep_get(user_agent_dict, ["user_agent", "patch"]),
        ip=client_ip,
        is_bot=is_bot(user_agent),
    )
    visit.save()
    return visit
    # except Exception as e:
    #     # something went wrong but we don't want to alert the visitor...
    #     logging.error(
    #         "Failed to save visit to {}. IP: {}, UA: {}".format(
    #             link, client_ip, user_agent
    #         )
    #     )
    #     logging.error(e)


def _save_visit_minimal(request, link):
    # Directly redirects visitor to the destination
    _save_data_from_request(request, link)
    return redirect(link.destination)


def _save_visit_extended(request, link):
    # Shows visitor an interstitial and uses Javascript to collect extra data
    visit = _save_data_from_request(request, link)
    request.session["visit_pk"] = visit.pk

    return render(
        request,
        "links/interstitial_blank.html",
        {"link": link, "ray_id": get_ray_id(), "visit": visit,},
    )


def redirect_to_destination(request, short_id):
    link = get_object_or_404(Link, short_id=short_id)
    if link.collect_extended_data:
        return _save_visit_extended(request, link)
    else:
        return _save_visit_minimal(request, link)


def update_visit(request):
    if request.method != "POST":
        raise Http404("Invalid method")

    data = json.loads(request.body)
    visit = get_object_or_404(Visit, pk=request.session["visit_pk"])

    visit.fingerprint_fields = data.get("fingerprint_fields", {})
    visit.fingerprint = data.get("fingerprint", "")
    visit.screen_x = data.get("width")
    visit.screen_y = data.get("height")
    visit.save()

    return HttpResponse(status=204)  # HTTP No Content

links/templates/links/admin/base.html
{% extends "redirekt/base.html" %}

{% block navbar %}
<nav class="navbar navbar-dark bg-dark">
  <a href="/links/admin" class="navbar-brand mb-0 h1">redirekt</a>
</nav>
{% endblock %}

links/templates/links/admin/create_link.html
{% extends "links/admin/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <form action="/links/admin/create/" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          Create link
        </button>
      {% endbuttons %}
  </form>
{% endblock %}

links/templates/links/admin/index.html
{% extends "links/admin/base.html" %}
{% block title %}redirekt{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <h1>Links</h1>
  </div>
  <div class="row mb-3">
    <a class="btn btn-primary" href="/links/admin/create/">Create new link</a>
  </div>
  <div class="row">
    {% if links %}
      <div class="table-responsive">
        <table class="table table-striped">
          <thead class="thead-light">
          <tr>
            <th>Name</th>
            <th>Created at</th>
            <th>ID</th>
            <th>Destination</th>
            <th>Visits</th>
            <th>Actions</th>
          </tr>
          </thead>
          {% for link in links %}
            <a href="{{ link.get_absolute_url }}">
              <tr>
                <td>{{ link.title }}</td>
                <td>{{ link.created_at }}</td>
                <td>{{ link.short_id }}</td>
                <td>{{ link.destination }}</td>
                <td>{{ link.visit_set.count }}</td>
                <td>
                  <a class="btn btn-outline-secondary" href="{{ link.get_absolute_url }}" alt="View">
                    <span class="oi oi-eye"></span>
                  </a>
                  <a class="btn btn-outline-danger" href="{{ link.get_absolute_url }}" alt="Delete">
                    <span class="oi oi-trash"></span>
                  </a>
                </td>
              </tr>
            </a>
          {% endfor %}

        </table>
      </div>
    {% else %}
      <div class="col-4 offset-4">
        <div class="alert alert-secondary" role="alert">
          No links found.
        </div>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

links/templates/links/admin/login.html
{% extends "links/admin/base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="container d-flex h-50 justify-content-center">
  <div class="row align-self-center">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Login</h5>
        <form action="/links/admin/login/" method="post">
          <div class="form-group">
            {% csrf_token %} {{ form }}
          </div>
          <input class="btn btn-primary" type="submit" value="Log in" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

links/templates/links/admin/view_link.html
{% extends "links/admin/base.html" %}

{% block content %}
  <div class="row">
    <h1>
      Link: {{ link.title }}
    </h1>
  </div>
  <div class="row">
    <ul>
      <li><b>Short URL</b>: <a href="{{ link.get_redirect_url }}">{{ link.get_redirect_url }}</a></li>
      <li><b>Destination</b>: {{ link.destination }}</li>
      <li><b>Created at</b>: {{ link.created_at }}</li>
    </ul>
  </div>
  <div class="row">
    <a href="/links/delete/{{ link.pk }}" class="btn btn-danger btn-sm">
      <span class="oi oi-trash"></span> Delete link
    </a>
  </div>
  <div class="row mt-2">
    <h2>Visits</h2>
  </div>
  <div class="row">
    {% if visits %}
      <table class="table table-bordered">
        <thead class="thead-light">
        <tr>
          <th>Timestamp</th>
          <th>User agent</th>
          <th>IP</th>
          <th>Hostname</th>
          <th>Location</th>
          <th>Coordinates</th>
          <th>Fingerprint</th>
        </tr>
      </thead>
      {% for visit in visits %}
        {% if visit.is_bot %}
          <tr class="table-secondary">
        {% else %}
          <tr>
        {% endif %}
          <td>{{ visit.created_at }}</td>
          {% if visit.is_bot %}
            <td>{{ visit.user_agent }} <span class="badge badge-pill badge-secondary">Bot</span></td>
          {% else %}
            <td>{{ visit.user_agent }}</td>
          {% endif %}
          <td>{{ visit.ip }}</td>
          <td>{{ visit.hostname }}</td>
          <td>{{ visit.city }}, {{ visit.country }}</td>
          <td>{{ visit.latitude }}, {{ visit.longitude }}</td>
          <td>{{ visit.fingerprint }}</td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
      <p>No visits yet.</p>
    {% endif %}
  </div>
{% endblock %}